### ISSUE TITLE
Multiple streams output to single file

### ISSUE THREAD

**Issue by Batuzz** [shaka-project/shaka-packager#1200] opened 2023-04-21 14:30 UTC
## System info
**Operating System**: macOS Monterey
**Shaka Packager Version**: v2.6.1-634af65-release

**Packager Command**:
```
shaka-packager 'in=avc_test.mp4,stream=video,segment_template=hls/360p_avc/$Number$.mp4,playlist_name=360p_avc/main.m3u8,init_segment=hls/360p_avc/test.mp4'
'in=avc_test.mp4,stream=audio,segment_template=hls/audio/$Number$.mp4,playlist_name=audio/main.m3u8,init_segment=hls/audio/test.mp4'
--segment_duration 2
--hls_master_playlist_output hls/master.m3u8
```

## Issue description
Hello,
I'm trying to package **video** AND **audio** streams into single segment file (HLS), eg:
```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-STREAM-INF:BANDWIDTH=3440800,RESOLUTION=270x480,CODECS="avc1.4d401e,mp4a.40.2"
audio-video/360/avc/stream.m3u8
```

All I was able to achieve is separate audio and video segments, eg:

```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-MEDIA:TYPE=AUDIO,URI="audio/main.m3u8",GROUP-ID="default-audio-group",NAME="stream_0",AUTOSELECT=YES,CHANNELS="1"

#EXT-X-STREAM-INF:BANDWIDTH=901048,AVERAGE-BANDWIDTH=838019,CODECS="avc1.64001e,mp4a.40.2",RESOLUTION=480x720,FRAME-RATE=30.000,VIDEO-RANGE=SDR,AUDIO="default-audio-group",CLOSED-CAPTIONS=NONE
360p_avc/main.m3u8
```

Is there any way to package both audio and video streams into single segment file?
If not, is there any reason not do to so, or is it just not supported yet?

**Comment by cosmin** [comment] 2024-04-26 00:37
duplicate of #802 which in summary is not something we are planning to support right now, or rather nobody is planning to work on it, pull requests are welcome.

**Closed by cosmin** 2024-04-26 00:37 UTC
Labels: status: duplicate
